/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "LCD_Char_1.h"
#include "UART_1.h"
#include "SPIM_1.h"
#include "SPIM_1_PVT.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "Pin_3_aliases.h"
#include "Pin_3.h"
#include "Pin_4_aliases.h"
#include "Pin_4.h"
#include "Pin_5_aliases.h"
#include "Pin_5.h"
#include "Pin_6_aliases.h"
#include "Pin_6.h"
#include "tx_int.h"
#include "rx_int.h"
#include "LCD_Char_1_LCDPort_aliases.h"
#include "LCD_Char_1_LCDPort.h"
#include "UART_1_IntClock.h"
#include "SPIM_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

