# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Hanna Lee\Documents\PSoC Creator\final_project\RF_Test.cydsn\RF_Test.cyprj
# Date: Wed, 11 May 2016 00:28:40 GMT
#set_units -time ns
create_clock -name {CyILO} -period 10000 -waveform {0 5000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyMASTER_CLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]
create_generated_clock -name {SPIM_1_IntClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 25 49} [list [get_pins {ClockBlock/dclk_glb_0}]]
create_generated_clock -name {UART_1_IntClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 625 1251} -nominal_period 13020.833333333332 [list [get_pins {ClockBlock/dclk_glb_1}]]


# Component constraints for C:\Users\Hanna Lee\Documents\PSoC Creator\final_project\RF_Test.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Hanna Lee\Documents\PSoC Creator\final_project\RF_Test.cydsn\RF_Test.cyprj
# Date: Wed, 11 May 2016 00:28:30 GMT
