/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "ADC_DelSig_1.h"
#include "VDAC8_1.h"
#include "SPIM_1.h"
#include "SPIM_1_PVT.h"
#include "MISO_aliases.h"
#include "MISO.h"
#include "MOSI_aliases.h"
#include "MOSI.h"
#include "SCLK_aliases.h"
#include "SCLK.h"
#include "CSN_aliases.h"
#include "CSN.h"
#include "CE_aliases.h"
#include "CE.h"
#include "ADC_Input_aliases.h"
#include "ADC_Input.h"
#include "DAC_Output_aliases.h"
#include "DAC_Output.h"
#include "tx_int.h"
#include "rx_int.h"
#include "UART_1_IntClock.h"
#include "ADC_DelSig_1_AMux.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "SPIM_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

